### ISSUE TITLE
Postgresql : "could not find driver" error

### ISSUE THREAD

**Issue by Rom1deTroyes** [Hywan/Database-to-PlantUML#10]
When I try to export my database I got this error :
```
~/src/Database-to-PlantUML (master)$ bin/database-to-plantuml -d 'pgsql:dbname=employees' -u api -s employees
could not find driver
```

What I've done :
  git clone https://github.com/Hywan/Database-to-PlantUML.git
  cd Database-to-PlantUML/
  composer install
  psql -h localhost -U api -d api -f resource/samples/pgsql-employees.sql

Everything goes well, and the datas are in the db,

Does the posgresql has to be installed elsewhere ?

**Comment by Hywan** [comment]
Hi :-),

Do you have PDO with Postgres installed in PHP?

**Comment by Rom1deTroyes** [comment]
Excuse me for the delay : I was working on an other project now and forgot to follow my question :-(

Today I had the same problem with a mysql database, and yes, there was no PDO in my php configuration !

**Comment by Hywan** [comment]
No need to be sorry.
